repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Gitleaks secret scan
        entry: gitleaks protect --staged --verbose --redact --config .gitleaks.toml
        language: system
        pass_filenames: false
